"""Build a one-folder Windows executable with PyInstaller (avoids "Failed to load Python DLL"
when run from Download and run). Run from project root."""

import os
import subprocess
import sys
import zipfile


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)

    # Entry script
    entry = "main.py"
    if not os.path.isfile(entry):
        print(f"Entry script not found: {entry}")
        sys.exit(1)

    # Optional icon (generated by tools/build_icon.py)
    icon_path = os.path.join(root, "where-songs-meet.ico")
    icon_arg = ["--icon", icon_path] if os.path.isfile(icon_path) else []

    # DPI-aware manifest (sharp rendering on high-DPI; v1.0.3 had this)
    manifest_path = os.path.join(root, "manifest.xml")
    manifest_arg = ["--manifest", manifest_path] if os.path.isfile(manifest_path) else []

    # Ensure PyInstaller is available
    try:
        import PyInstaller.__main__
    except ImportError:
        print("PyInstaller required: pip install pyinstaller")
        sys.exit(1)

    # Hidden imports for dynamic/optional modules
    hidden = [
        "--hidden-import", "midi_to_macro.theme",
        "--hidden-import", "midi_to_macro.icon_images",
    ]

    # One-folder (onedir) so exe runs with DLLs beside it — no temp extraction, no "Failed to load Python DLL"
    cmd = (
        [
            sys.executable, "-m", "PyInstaller",
            "--onedir",
            "--windowed",
            "--name", "where-songs-meet",
            "--clean",
            "--noconfirm",
        ]
        + icon_arg
        + manifest_arg
        + hidden
        + [entry]
    )

    print("Running:", " ".join(cmd))
    result = subprocess.run(cmd, cwd=root)
    if result.returncode != 0:
        sys.exit(result.returncode)

    dir_path = os.path.join(root, "dist", "where-songs-meet")
    exe_path = os.path.join(dir_path, "where-songs-meet.exe")
    zip_path = os.path.join(root, "dist", "where-songs-meet.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for dirpath, _dirnames, filenames in os.walk(dir_path):
            for name in filenames:
                path = os.path.join(dirpath, name)
                arcname = os.path.join("where-songs-meet", os.path.relpath(path, dir_path))
                zf.write(path, arcname)
    print("Built folder:", dir_path)
    print("Built zip:", zip_path)


if __name__ == "__main__":
    main()
